version: 0.2

env:
  secrets-manager:
    SECRET_KEY: "django_secret_key:DJANGO_SECRET_KEY"
    DB_PASSWORD: "django_secret_key:DJANGO_DB_PASSWORD"
  variables:
    DB_NAME: "django"
    DB_USER: "admin"
    DB_HOST: "django.camau3gpp4an.us-east-1.rds.amazonaws.com"
    DB_PORT: "3306"

batch:
  fast-fail: true
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.x
  build:
    on-failure: ABORT
    commands:
      - pip3 install -r requirements.txt
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - '**/*'