version: 0.2

env:
  secrets-manager:
    SECRET_KEY: "django_secret_key:SECRET_KEY"

batch:
  fast-fail: true
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.x
    commands:
      - yum install python3 -y
      - yum install SQLite -y
  pre_build:
    on-failure: ABORT
    commands:
      - pip3 install -r requirements.txt
  build:
    on-failure: ABORT
    commands:
      - gunicorn test_django.wsgi
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`